name: JSUtilities
version: {project.version}
author: JieSheng03
main: io.github.jieshengnp.jsutilities.JSUtilities
api-version: 1.16
commands:
  heal:
    usage: /<command> [PlayerName]
    description: Heals Player.
  feed:
    usage: /<command> [PlayerName]
    description: Feeds Player.
  getpos:
    usage: /<command> [PlayerName]
    description: Gets Player Position.