name: JSUtilities
version: 1.2.2
author: JieSheng03
main: io.github.jieshengnp.jsutilities.JSUtilities
api-version: 1.16
commands:
  heal:
    usage: /<command> [PlayerName]
    description: Heals Player.
  feed:
    usage: /<command> [PlayerName]
    description: Feeds Player.